version: "3.7"

services:
  app:
    build: ./docker
    image: callmedavid/bkphones
    container_name: bkphones
    ports:
      - "8000:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
      
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc
      MYSQL_USER: php_mvc
      MYSQL_PASSWORD: php_mvc

volumes:
  mysql-data: